services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always

volumes:
  mongodb_data:
    external: false
